### ISSUE TITLE
有時候用 Chrome 瀏覽器時，會無法投稿

### ISSUE THREAD

**Issue by ddio** [g0v/summit_proposal#26]
## 重製步驟

1. 用 Chrome + slack 登入
2. 點「我要投稿」
3. 預期會出現投稿畫面，但在出現標頭後，網頁就跳回首頁了

https://g0v-tw.slack.com/files/UPNN3C1FZ/F0169BT5G1Z/screen_recording_2020-06-29_at_10.25.00_pm.mov

**Comment by ddio** [comment]
## 重製步驟

1. 確定在登出狀態
1. 點我要投稿
1. 看到登入畫面，使用 google 帳號登入
1. 看到首頁，點「我要投稿」
1. 預期看到投稿畫面，但

**Comment by ddio** [comment]
### 事發原因

1. 我們會把最後 && 未提交的 project id 存在 local storage
2. 我們會在打開編輯畫面前，檢查此 project 是否屬於目前登入的帳號，如果不是，則回到首頁
3. 當
   1. 使用者用 A 帳號投稿 && 尚未送出
   2. 切換成 B 帳號，又點投稿時
   3. 因為 A 的 project id 還存在 local storage 裡，但進去編輯就會被踢出來，所以會出現原文影片的狀況

### 暫時解法

1. 發現 project 權限錯誤時，不直接回到首頁，而是送出 `access-denied` 給 parent component
2. `ProposalCreate` 吃到時，代表換帳號登入了，換一個新 project id
3. `ProposalEdit` 吃到時，表示有人在惡搞系統，直接回到提案列表

### 可能待作

1. 不確定大家會不會對用同樣 email ，但不同 provider 登入，卻無法編輯同一個專案感到困惑 @tnstiger  XD

**Comment by tnstiger** [comment]
不同第三方登入是屬於不同的帳號，若他用不同的第三方登入，不能編輯也是挺正常的，市面上的行為把它當作不同帳號的也有，自動做帳號鏈結的也有，所以應該還能想像。
