### ISSUE TITLE
加強投稿清單的過濾功能

### ISSUE THREAD

**Issue by ddio** [g0v/summit_proposal#29]
在投稿頁面中：

1. 增加下拉選單，讓人可以依照投稿形式篩選投稿，單選可，多選為佳
2. 增加下拉選單，讓人可以依照投稿主題分類篩選投稿，單選可，多選為佳
3. 選項同時顯示華英雙語
4. 這張票不用處理搜尋、清單模式
5. 詳細規格請見 wireframe
6. 與網址雙向綁定

Wireframe: 

- https://app.moqups.com/E5CfqelG3u/view/page/ad64222d5
- 
![2020-07-07 12-46-47 的螢幕擷圖](https://user-images.githubusercontent.com/271157/86712800-fbf04b80-c04f-11ea-8081-18b17a52e470.png)

**Comment by ddio** [comment]
可考慮把欄位定義檔從 ProposalForm 裡抽出來，這樣就不用重複翻譯欄位～
https://github.com/g0v/summit_proposal/blob/d8012bee68425803e1b9c1c1f9123eb5255abab5/src/components/proposalForm/ProposalForm.vue#L62

**Comment by UnaLai** [comment]
已加上投稿清單的過濾功能。
