### ISSUE TITLE
加強投稿清單的搜尋功能

### ISSUE THREAD

**Issue by ddio** [g0v/summit_proposal#35]
在投稿頁面中：

1. 讓搜尋支援全文搜尋
3. 選項同時顯示華英雙語
4. 這張票不用處理下拉式過濾選單、清單模式
5. 詳細規格請見 wireframe

Wireframe: 

- https://app.moqups.com/E5CfqelG3u/view/page/ad64222d5
- 
![2020-07-07 12-46-47 的螢幕擷圖](https://user-images.githubusercontent.com/271157/86712800-fbf04b80-c04f-11ea-8081-18b17a52e470.png)

**Comment by UnaLai** [comment]
已加強投稿清單的搜尋功能。
