### ISSUE TITLE
預設顯示投稿清單，而不是卡片

### ISSUE THREAD

**Issue by ddio** [g0v/summit_proposal#36]
為了讓人一次可以看到更多投稿資訊，鼓勵互動，在投稿頁面中：

1. 預設顯示清單模式
2. 加寬最大寬度
3. 可以切換回卡片模式
4. 每頁數量調整為 20 個，或與卡片模式相容的數量
5. 詳細規格請見 wireframe
6. 與網址雙向綁定

Wireframe: 

- https://app.moqups.com/E5CfqelG3u/view/page/ad64222d5
- 
![2020-07-07 12-46-47 的螢幕擷圖](https://user-images.githubusercontent.com/271157/86712800-fbf04b80-c04f-11ea-8081-18b17a52e470.png)

**Comment by UnaLai** [comment]
已加上預設顯示投稿清單。
