### ISSUE TITLE
顯示此帳號的討論區未讀訊息數

### ISSUE THREAD

**Issue by ddio** [g0v/summit_proposal#38]
身為一個有參與討論的鄉民，我想知道是否有討論區有我的未讀訊息，讓我即時知道更新狀況

### 目標：

1. 若為登入狀態，用 [NodeBB Notification API](https://docs.nodebb.org/api/#tag/notifications/paths/~1api~1notifications/get) ，在 banner 的「討論區」區塊，顯示該使用者的討論區未讀訊息數（和 Facebook 一樣，在右下角有個紅底白字圈圈的那種）

此 API 需要登入 nodebb ，但 staging 環境的雙向登入似乎有點問題，還需要詢問 Howard XD 

### 相關資訊：

1. 關於在 Vue 裡使用 API ，請見 [FORUM_API.js](https://github.com/g0v/summit_proposal/blob/develop/src/utils/FORUM_API.js)

**Comment by tnstiger** [comment]
@ddio 因為 stage 那邊的 cros 忘記跟著 production 一起打開，我剛剛測試ＯＫ了，你再試試看
記得送 credentials: 'include'

fetch(`https://discuss.summit2020.pre-stage.cc/api/notifications`, 
    {
        method: 'GET',
        credentials: 'include'
    }
)

**Comment by ddio** [comment]
感謝！
