### ISSUE TITLE
Difficult to close version popup

### ISSUE THREAD

**Issue by kota-yata** [g0v/summit_proposal#40]
When you open the version detail popup, the close button is too difficult to close on mobile or even desktop. I want to close this popup when I click the background.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51294895/87048515-c6598700-c236-11ea-8342-fe18da6a6147.png">

**Comment by ddio** [comment]
PR deployed to production. Thanks @kota-yata !
